-- Seed fake data for categories and hashtags (demo/dev only)

-- total categories: 46
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Artificial Intelligence', 'artificial-intelligence', 'Everything about AI models, research and real-world use', NULL, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Web Development', 'web-development', 'Front-end, back-end and full-stack engineering notes', NULL, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Mobile Development', 'mobile-development', 'Native and cross-platform mobile app engineering', NULL, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('DevOps & Cloud', 'devops-cloud', 'Infrastructure, deployment pipelines and cloud platforms', NULL, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Data & Analytics', 'data-analytics', 'Data engineering, analytics and visualization', NULL, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Cybersecurity', 'cybersecurity', 'Application security, pentesting and best practices', NULL, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Productivity', 'productivity', 'Tools and workflows for getting more done', NULL, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Career & Learning', 'career-learning', 'Career growth, interviews and learning resources', NULL, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Startups & Business', 'startups-business', 'Building and running a tech business', NULL, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Gadgets & Reviews', 'gadgets-reviews', 'Hardware and software product reviews', NULL, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Open Source', 'open-source', 'Open source projects, contributions and licensing', NULL, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Programming Languages', 'programming-languages', 'Language deep-dives, comparisons and idioms', NULL, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Large Language Models', 'artificial-intelligence-large-language-models', 'Large Language Models articles under Artificial Intelligence', 1, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Machine Learning', 'artificial-intelligence-machine-learning', 'Machine Learning articles under Artificial Intelligence', 1, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Prompt Engineering', 'artificial-intelligence-prompt-engineering', 'Prompt Engineering articles under Artificial Intelligence', 1, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('AI Agents', 'artificial-intelligence-ai-agents', 'AI Agents articles under Artificial Intelligence', 1, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Frontend Frameworks', 'web-development-frontend-frameworks', 'Frontend Frameworks articles under Web Development', 2, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Backend APIs', 'web-development-backend-apis', 'Backend APIs articles under Web Development', 2, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('CSS & Design Systems', 'web-development-css-design-systems', 'CSS & Design Systems articles under Web Development', 2, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Web Performance', 'web-development-web-performance', 'Web Performance articles under Web Development', 2, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('iOS Development', 'mobile-development-ios-development', 'iOS Development articles under Mobile Development', 3, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Android Development', 'mobile-development-android-development', 'Android Development articles under Mobile Development', 3, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Flutter', 'mobile-development-flutter', 'Flutter articles under Mobile Development', 3, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Containers & Kubernetes', 'devops-cloud-containers-kubernetes', 'Containers & Kubernetes articles under DevOps & Cloud', 4, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('CI/CD Pipelines', 'devops-cloud-ci-cd-pipelines', 'CI/CD Pipelines articles under DevOps & Cloud', 4, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('AWS', 'devops-cloud-aws', 'AWS articles under DevOps & Cloud', 4, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Infrastructure as Code', 'devops-cloud-infrastructure-as-code', 'Infrastructure as Code articles under DevOps & Cloud', 4, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Data Engineering', 'data-analytics-data-engineering', 'Data Engineering articles under Data & Analytics', 5, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('SQL & Databases', 'data-analytics-sql-databases', 'SQL & Databases articles under Data & Analytics', 5, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Data Visualization', 'data-analytics-data-visualization', 'Data Visualization articles under Data & Analytics', 5, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Application Security', 'cybersecurity-application-security', 'Application Security articles under Cybersecurity', 6, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Penetration Testing', 'cybersecurity-penetration-testing', 'Penetration Testing articles under Cybersecurity', 6, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Cryptography', 'cybersecurity-cryptography', 'Cryptography articles under Cybersecurity', 6, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Automation Tools', 'productivity-automation-tools', 'Automation Tools articles under Productivity', 7, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Note Taking', 'productivity-note-taking', 'Note Taking articles under Productivity', 7, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Technical Interviews', 'career-learning-technical-interviews', 'Technical Interviews articles under Career & Learning', 8, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Remote Work', 'career-learning-remote-work', 'Remote Work articles under Career & Learning', 8, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Product Management', 'startups-business-product-management', 'Product Management articles under Startups & Business', 9, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Fundraising', 'startups-business-fundraising', 'Fundraising articles under Startups & Business', 9, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Laptops', 'gadgets-reviews-laptops', 'Laptops articles under Gadgets & Reviews', 10, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Smartphones', 'gadgets-reviews-smartphones', 'Smartphones articles under Gadgets & Reviews', 10, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Open Source Licensing', 'open-source-open-source-licensing', 'Open Source Licensing articles under Open Source', 11, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Python', 'programming-languages-python', 'Python articles under Programming Languages', 12, 0);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('JavaScript & TypeScript', 'programming-languages-javascript-typescript', 'JavaScript & TypeScript articles under Programming Languages', 12, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Rust', 'programming-languages-rust', 'Rust articles under Programming Languages', 12, 1);
INSERT INTO categories (name, slug, description, parent_id, visible) VALUES ('Go', 'programming-languages-go', 'Go articles under Programming Languages', 12, 1);
-- total hashtags: 51
INSERT INTO hashtags (name, slug, description, active) VALUES ('ChatGPT', 'chatgpt', 'Posts and updates tagged ChatGPT', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Claude', 'claude', 'Posts and updates tagged Claude', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Gemini', 'gemini', 'Posts and updates tagged Gemini', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('LLM', 'llm', 'Posts and updates tagged LLM', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Prompt Engineering', 'prompt-engineering', 'Posts and updates tagged Prompt Engineering', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('AI Agents', 'ai-agents', 'Posts and updates tagged AI Agents', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Machine Learning', 'machine-learning', 'Posts and updates tagged Machine Learning', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Deep Learning', 'deep-learning', 'Posts and updates tagged Deep Learning', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Computer Vision', 'computer-vision', 'Posts and updates tagged Computer Vision', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('NLP', 'nlp', 'Posts and updates tagged NLP', 0);
INSERT INTO hashtags (name, slug, description, active) VALUES ('OpenAI', 'openai', 'Posts and updates tagged OpenAI', 0);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Anthropic', 'anthropic', 'Posts and updates tagged Anthropic', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Hugging Face', 'hugging-face', 'Posts and updates tagged Hugging Face', 0);
INSERT INTO hashtags (name, slug, description, active) VALUES ('LangChain', 'langchain', 'Posts and updates tagged LangChain', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('RAG', 'rag', 'Posts and updates tagged RAG', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Fine Tuning', 'fine-tuning', 'Posts and updates tagged Fine Tuning', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('JavaScript', 'javascript', 'Posts and updates tagged JavaScript', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('TypeScript', 'typescript', 'Posts and updates tagged TypeScript', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Python', 'python', 'Posts and updates tagged Python', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Rust', 'rust', 'Posts and updates tagged Rust', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Go', 'go', 'Posts and updates tagged Go', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Java', 'java', 'Posts and updates tagged Java', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Kotlin', 'kotlin', 'Posts and updates tagged Kotlin', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Swift', 'swift', 'Posts and updates tagged Swift', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('React', 'react', 'Posts and updates tagged React', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Vue', 'vue', 'Posts and updates tagged Vue', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Angular', 'angular', 'Posts and updates tagged Angular', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Next.js', 'next-js', 'Posts and updates tagged Next.js', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Node.js', 'node-js', 'Posts and updates tagged Node.js', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Spring Boot', 'spring-boot', 'Posts and updates tagged Spring Boot', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Docker', 'docker', 'Posts and updates tagged Docker', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Kubernetes', 'kubernetes', 'Posts and updates tagged Kubernetes', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Terraform', 'terraform', 'Posts and updates tagged Terraform', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('AWS', 'aws', 'Posts and updates tagged AWS', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('CI/CD', 'ci-cd', 'Posts and updates tagged CI/CD', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('GitHub Actions', 'github-actions', 'Posts and updates tagged GitHub Actions', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('PostgreSQL', 'postgresql', 'Posts and updates tagged PostgreSQL', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('MySQL', 'mysql', 'Posts and updates tagged MySQL', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('MongoDB', 'mongodb', 'Posts and updates tagged MongoDB', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Redis', 'redis', 'Posts and updates tagged Redis', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Data Science', 'data-science', 'Posts and updates tagged Data Science', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Cybersecurity', 'cybersecurity', 'Posts and updates tagged Cybersecurity', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Penetration Testing', 'penetration-testing', 'Posts and updates tagged Penetration Testing', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Encryption', 'encryption', 'Posts and updates tagged Encryption', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Open Source', 'open-source', 'Posts and updates tagged Open Source', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Git', 'git', 'Posts and updates tagged Git', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Linux', 'linux', 'Posts and updates tagged Linux', 0);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Startup', 'startup', 'Posts and updates tagged Startup', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Product Management', 'product-management', 'Posts and updates tagged Product Management', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Remote Work', 'remote-work', 'Posts and updates tagged Remote Work', 1);
INSERT INTO hashtags (name, slug, description, active) VALUES ('Career Growth', 'career-growth', 'Posts and updates tagged Career Growth', 1);
