{{-- Table of Contents --}}
<div class="sidebar-widget sidebar-toc-widget">
    <h3 class="sidebar-widget-title d-block" onclick="toggleTOC()">
        <div class="d-flex align-items-center justify-content-between">
            <span class="sidebar-widget-title-text">
                <i class="bx bx-list-ul"></i>
                Mục lục
            </span>
            <button class="sidebar-widget-toggle collapsed" type="button"
                aria-label="Đóng/Mở mục lục">
                <i class="bx bx-chevron-down"></i>
            </button>
        </div>
    </h3>
    <div class="sidebar-widget-content collapsed" id="toc-content">
        <ul class="toc-list" id="toc-list">
            {{-- TOC will be generated by JavaScript --}}
        </ul>
    </div>
</div>

